###############################################################
# Copyright (C) 2018 Robert Hansel
# 
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
##############################################################
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below